<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_pwd</name>
   <tag></tag>
   <elementGuidId>6267b239-44ff-4da8-a063-a04e105a77d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pwd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pwd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aa8f99e-5e87-465d-bd7b-5b304003ed10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0552e4be-69ac-47a5-87fb-e650ec5eedf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwd</value>
      <webElementGuid>f781587b-3d85-4645-98e9-abfe6910ea44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>7729428d-7eb9-4cc3-84a6-33c77cd708b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwd</value>
      <webElementGuid>592afca1-81d2-4651-9602-fe83056b0072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pwd&quot;)</value>
      <webElementGuid>e67b0856-b248-4082-8fa0-c350645a1c61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pwd']</value>
      <webElementGuid>1a3f08a0-24bb-48ae-8b70-12668bebce6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>94fa7b3b-2572-4976-bc8b-e9cf8d863668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pwd' and @placeholder = 'test' and @name = 'pwd']</value>
      <webElementGuid>ac616982-c38c-4ab8-b57e-c042e5184790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
